export const USER_LOGIN_ID = "USER_LOGIN_ID";
export const USER_DATA = "USER_DATA";

export const SET_JWT_TOKEN = "SET_JWT_TOKEN";
export const REMOVE_JWT_TOKEN = "REMOVE_JWT_TOKEN";
export const SET_USER_INFO = "SET_USER_INFO";

export const SET_QUIZ_ID = "SET_QUIZ_ID";

export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAILURE = "CREATE_QUIZ_FAILURE";
export const REMOVE_LAST_QUESTION = "REMOVE_LAST_QUESTION";

export const GET_AVAILABLE_QUIZZES_SUCCESS = "GET_AVAILABLE_QUIZZES_SUCCESS";
export const GET_AVAILABLE_QUIZZES_FAILURE = "GET_AVAILABLE_QUIZZES_FAILURE";

export const GET_TEACHER_QUIZZES = "GET_TEACHER_QUIZZES";

export const SUBMIT_QUIZ_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_QUIZ_FAILURE = "SUBMIT_QUIZ_FAILURE";

export const FETCH_QUIZ_RESULT_SUCCESS = "FETCH_QUIZ_RESULT_SUCCESS";
export const FETCH_QUIZ_RESULT_FAILURE = "FETCH_QUIZ_RESULT_FAILURE";

export const FETCH_QUIZZES_SUCCESS = "FETCH_QUIZZES_SUCCESS";
export const FETCH_QUIZZES_FAILURE = "FETCH_QUIZZES_FAILURE";

export const FETCH_STUDENT_QUIZZES_SUCCESS = "FETCH_STUDENT_QUIZZES_SUCCESS";
export const FETCH_STUDENT_QUIZZES_FAILURE = "FETCH_STUDENT_QUIZZES_FAILURE";

export const FETCH_STUDENT_ASSIGNMENTS_SUCCESS = "FETCH_STUDENT_ASSIGNMENTS_SUCCESS";
export const GET_TEACHER_ASSIGNMENTS = "GET_TEACHER_ASSIGNMENTS";
export const SET_ASSIGNMENT_ID = "SET_ASSIGNMENT_ID";

export const FETCH_ATTEMPTED_QUIZZES_SUCCESS =
  "FETCH_ATTEMPTED_QUIZZES_SUCCESS";
export const FETCH_ATTEMPTED_QUIZZES_FAILURE =
  "FETCH_ATTEMPTED_QUIZZES_FAILURE";

export const FETCH_QUIZ_RESULT_FOR_STUDENT_SUCCESS =
  "FETCH_QUIZ_RESULT_FOR_STUDENT_SUCCESS";
export const FETCH_QUIZ_RESULT_FOR_STUDENT_FAILURE =
  "FETCH_QUIZ_RESULT_FOR_STUDENT_FAILURE";

export const STORE_ANSWER = "STORE_ANSWER";
export const FETCH_QUIZ_DETAILS = "FETCH_QUIZ_DETAILS";

export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const UPDATE_ANSWER_EMPTY = "UPDATE_ANSWER";

export const START_QUIZ_TIMER = "START_QUIZ_TIMER";
export const STOP_QUIZ_TIMER = "STOP_QUIZ_TIMER";
export const SET_QUIZ_TIMER = "SET_QUIZ_TIMER";
export const DECREMENT_QUIZ_TIMER = "DECREMENT_QUIZ_TIMER";
export const RESET_QUIZ_TIMER = "RESET_QUIZ_TIMER";
export const UPDATE_REMAINING_TIME = "UPDATE_REMAINING_TIME";
export const SET_QUIZ_IN_PROGRESS = "SET_QUIZ_IN_PROGRESS";
export const RESET_QUIZ_IN_PROGRESS = "RESET_QUIZ_IN_PROGRESS";

